### ISSUE TITLE
Trying to get Avalara to play nice but has hashie gem issue

### ISSUE THREAD

**Issue by thomasjoyce** [adamfortuna/avalara#14]
Hi,

I just try to use this gem and initially there was a hashie gem issue where it could not load file. 

Not sure what that mean? Any pointers? not familiar with hashie gem. 
Thanks for your help and creating this Avalara gem :- ) 

Tried this example: got Avalara return nil. (not sure if it did send to Avalara at all)
irb(main):008:0> result = Avalara.geographical_tax('47.627935', '-122.51702', 100)
=> #<Avalara::Response::Tax>

Tried the second example,  got this error "Avalara::Error: cannot load such file -- hashie/extensions/symbolize_keys"

=> #<Avalara::Request::Invoice Addresses=[#<Avalara::Request::Address AddressCode=1 Line1="435 Ericksen Avenue Northeast" Line2="#250" PostalCode="98110">] CompanyCode=1 DocDate="2015-09-28" Lines=[#<Avalara::Request::Line Amount=10 DestinationCode="1" LineNo="1" OriginCode="1" Qty="1">]>
irb(main):078:0> result = Avalara.get_tax(invoice) 
Avalara::Error: cannot load such file -- hashie/extensions/symbolize_keys
	from /Users/tomtom/workplace/xxx/vendor/gems/avalara/lib/avalara.rb:101:in `rescue in get_tax'
	from /Users/tomtom/workplace/xxx/vendor/gems/avalara/lib/avalara.rb:80:in `get_tax'
	from (irb):78
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands/console.rb:47:in `start'
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands/console.rb:8:in `start'
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
irb(main):079:0>

**Comment by adamfortuna** [comment]
That's not good! What version of the gem and hashie are you using? I see there's not a decent version lock for hashie which might be an issue. Looks like the current hashie version on master is using hashie (3.4.1).

https://github.com/adamfortuna/avalara/blob/master/Gemfile.lock#L20

**Comment by thomasjoyce** [comment]
i did some debug and saw that i got response back from Avalara rest api with response back successful. 

it is failing on " Response::Invoice.new(response)" https://github.com/adamfortuna/avalara/blob/master/lib/avalara.rb#L90

Response i'm getting back from Avalara:
```
Date: Tue, 29 Sep 2015 21:42:07 GMT
User-Agent: avalara/0.1.1 (Rubygems; Ruby 1.9.3 x86_64-darwin14.1.0)
Content-Length: '281'
TAXXXXX CALCULATE authentication: ---
:username: xxx
:password: xxx
TAXXXXX CALCULATE response 2: ---
ResultCode: Success
DocCode: abf40bcc-8b2d-4d97-9a54-4ec30ec209ed
DocDate: '2015-09-29'
Timestamp: '2015-09-29T21:43:17.8520571Z'
TotalAmount: '10'
TotalDiscount: '0'
TotalExemption: '0'
TotalTaxable: '10'
TotalTax: '0.95'
TotalTaxCalculated: '0.95'
TaxLines:
- LineNo: '1'
  TaxCode: P0000000
  Taxability: 'true'
  BoundaryLevel: Address
  Exemption: '0'
  Discount: '0'
  Taxable: '10'
  Rate: '0.095000'
  Tax: '0.95'
  TaxCalculated: '0.95'
  TaxDetails:
  - Country: US
    Region: WA
    JurisType: State
    JurisCode: '53'
    Taxable: '10'
    Rate: '0.065000'
    Tax: '0.65'
    JurisName: WASHINGTON
    TaxName: WA STATE TAX
  - Country: US
    Region: WA
    JurisType: Special
    JurisCode: L3131
    Taxable: '10'
    Rate: '0.030000'
    Tax: '0.3'
    JurisName: SNOHOMISH-PTBA
    TaxName: WA SPECIAL TAX
TaxAddresses:
- Address: 2001 Palo Dr
  AddressCode: '1'
  City: Bothell
  Country: US
  PostalCode: 98012-6458
  Region: WA
  TaxRegionId: '2109967'
  JurisCode: '5306100000'
TaxDate: '2015-09-29'
```

with this error: 
Avalara::Error: cannot load such file -- hashie/extensions/symbolize_keys
	from /Users/tomtom/workplace/xxx/vendor/gems/avalara/lib/avalara.rb:116:in `rescue in get_tax'
	from /Users/tomtom/workplace/xxx/vendor/gems/avalara/lib/avalara.rb:80:in `get_tax'
	from (irb):30
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands/console.rb:47:in `start'
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands/console.rb:8:in `start'
	from /Users/tomtom/.rvm/gems/ruby-1.9.3-p286@xxx/gems/railties-3.2.11/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

Just wondering are the keys not matching with the definition? not familiar with hashie gems or this error meaning "Avalara::Error: cannot load such file -- hashie/extensions/symbolize_keys". 
Any pointers? i'm using gem hashie version [ gem 'hashie', '2.1.1' ]
